ProxyObject.RProxyPort = 9884;
ProxyObject.RAutoDetectProxy = true;
ProxyObject.RCutContentList = "video/x-flv|application/x-shockwave-flash|video/mpeg4|video/mp4|application/csv|video/x-matroska|video/mp2t|";
ProxyObject.RCutContentMaxSize = 3008;
ProxyObject.RProxyTransparent = false;
ProxyObject.RUrlFilters = ";*google*/*;*microsoft*/*;https://ssl.gstatic.com*;http://api.bing.com/qsml.aspx*;www.download.windowsupdate.com;https://www.gstatic.com*;us.update.toolbar.com;toolbar.msn.com;g.msn;skype.com;*.skype.com;outlook.com;*.outlook.com;office365.com;*.office365.com;*/autodiscover/autodiscover.xml;";
ProxyObject.RProxyNegotiateBypass = false;
ProxyObject.RProxySSLServerCertiKeyFile = "C:\\Program Files (x86)\\RadView\\WebLOAD\\bin\\Certificates\\server.pem";
ProxyObject.RProxySSLServerCertiKeyFilePasswd = "password";
ProxyObject.RProxySSLTrustedCAsFile = "C:\\Program Files (x86)\\RadView\\WebLOAD\\bin\\Certificates\\root.pem";
ProxyObject.Run();
